# Build a Java application container with Gradle and Jib
## 
image: gradle:6.6-jdk8

stages:
  - build

Build Image :
  stage: build
  script:
  - gradle jib -Djib.to.image=$CI_REGISTRY_IMAGE:$CI_BUILD_REF -Djib.to.auth.username=$CI_REGISTRY_USER -Djib.to.auth.password=$CI_REGISTRY_PASSWORD
